### ISSUE TITLE
Add extended informations to paging

### ISSUE THREAD

**Issue by reneol** [ambermoon/xbmc_plugin_video_srf_podcast_ch#11]
As an user it would be useful to know, what number has the next page.

Now it looks like this:

```
"Arena vom 08.01.2016"
"Arena vom 18.12.2015"
"Ältere Folgen dieser Sendung anzeigen.."
```

An improvement can be:

```
"Arena vom 08.01.2016"
"Arena vom 18.12.2015"
"Nächste Seite (2).."

...

"Arena vom 11.12.2015"
"Arena vom 04.12.2015"
"Nächste Seite (3).."

...
```

With this improvement the user can see at anytime on which page he is.

**Comment by ambermoon** [comment]
Thanks for the hint. I added the additional information.

Best Regards,

 Christian
