### ISSUE TITLE
KODI throws an error in line 79 in method listEpisodes in some cases

### ISSUE THREAD

**Issue by reneol** [ambermoon/xbmc_plugin_video_srf_podcast_ch#12]
Because of a bug inside the integrationlayer-API from SRF or faulty datasets, some showlists don't have the @maxpages-attribute, allthough they have more than one page.
You can see this bug in channel RSI, show "60Minuti":

```
http://il.srf.ch/integrationlayer/1.0/ue/rsi/assetSet/listByAssetGroup/3567604.json
```

Because of this KODI throws an error in line 79 in method listEpisodes

```
maxpage = response["AssetSets"]["@maxPageNumber"]
```

To prevent this error do the following:

```
    try:
        maxpage = response["AssetSets"]["@maxPageNumber"]
    except:
        maxpage = 1
```

The only limitation of this solution is, that in this case there is no paging, but i think it's ok.

**Comment by ambermoon** [comment]
I added your hint.
Thanks for your support, sorry for the slow response.
