### ISSUE TITLE
List TV show url does not work anymore

### ISSUE THREAD

**Issue by ManBehindMooN** [ambermoon/xbmc_plugin_video_srf_podcast_ch#22]
The url https://il.srgssr.ch/integrationlayer/1.0/ue/srf/tv/assetGroup/editorialPlayerAlphabetical.json returns a 404. 

https://il.srgssr.ch/integrationlayer/1.0/ue/srf/tv/assetGroup/ seems to work.

Quickfix addon.py line 56
change url = 'http://il.srgssr.ch/integrationlayer/1.0/ue/' + channel + '/tv/assetGroup/editorialPlayerAlphabetical.json'
to url = 'http://il.srgssr.ch/integrationlayer/1.0/ue/' + channel + '/tv/assetGroup/'

**Comment by HATT0R1HANZ0** [comment]
Thanks for the fix ManBehindMooN -> and also for the new Kodi Matrix Addon
Cheers

**Comment by ManBehindMooN** [comment]
My pleasure!
