### ISSUE TITLE
Make list size for selected show configurable

### ISSUE THREAD

**Issue by reneol** [ambermoon/xbmc_plugin_video_srf_podcast_ch#3]
If i select an show, for example 'Mini Beiz, Dini Beiz', then i have per default 10 list entries.
As an user i want to configure this. 
Make it possible to change this default in plugin config with an predefined choice-list with this entries: 5, 10, 25, 50,...

In your requests you can add an paramter to get the desired results:

http://il.srf.ch/integrationlayer/1.0/ue/srf/assetSet/listByAssetGroup/c635d4ac-5150-0001-d893-161035f0cdd0.json?pageSize=5

Also combining of request-parameters is possible

http://il.srf.ch/integrationlayer/1.0/ue/srf/assetSet/listByAssetGroup/c635d4ac-5150-0001-d893-161035f0cdd0.json?pageSize=5&pageNumber=3

**Comment by ambermoon** [comment]
Added first implementation.
