### ISSUE TITLE
Add extended informations to the title of episodes

### ISSUE THREAD

**Issue by reneol** [ambermoon/xbmc_plugin_video_srf_podcast_ch#7]
Now you only list the simple title of each episode, for example:

"SRF bi de Lüt vom 18.12.2015"

But it can be useful to see more informations there:

"SRF bi de Lüt vom 18.12.2015 - «SRF bi de Lüt – Die Weihnachtszauberer»: Folge 2"

To do this, add the following to your code in method 'listEpisodes':

```
    ...

    try:
        titleextended = ' - ' + episode['Assets']['Video'][0]['AssetMetadatas']['AssetMetadata'][0]['title']
    except:
        titleextended = ''

    ...

    addLink(title+titleextended, url, 'playepisode', desc, picture, length, pubdate,showbackground,channel)
```

**Comment by ambermoon** [comment]
Thanks for the hint. I added the additional title based on your input.

Best Regards,

 Christian
